### ISSUE TITLE
Issue with loading the models error

### ISSUE THREAD

**Issue by Dxtrmst** [GrandaddyShmax/audiocraft_plus#11]
Hi Bro,

I know youu've been working hard to improve.
I encountered an error this morning. Please see below.

Loading model melody
Downloading (…)ssion_state_dict.bin: 100% 236M/236M [00:01<00:00, 208MB/s]
Downloading state_dict.bin: 100% 2.77G/2.77G [00:26<00:00, 103MB/s]
Downloading: "https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/955717e8-8726e21a.th" to /root/.cache/torch/hub/checkpoints/955717e8-8726e21a.th
100% 80.2M/80.2M [00:00<00:00, 96.4MB/s]
Downloading (…)ve/main/spiece.model: 100% 792k/792k [00:00<00:00, 8.28MB/s]
Downloading (…)lve/main/config.json: 100% 1.21k/1.21k [00:00<00:00, 8.98MB/s]
Downloading model.safetensors: 100% 892M/892M [00:10<00:00, 83.4MB/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/content/audiocraft_plus/app.py", line 634, in predict_full
    load_model(model, custom_model, base_model)
  File "/content/audiocraft_plus/app.py", line 152, in load_model
    MODEL.lm.load_state_dict(torch.load("models/" + str(version) + ".pt"))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/melody.pt'

**Comment by Dxtrmst** [comment]
just solved it. i found you have a minor update. so we need to set these two to be same.


![image](https://github.com/GrandaddyShmax/audiocraft_plus/assets/98877199/6c585eeb-1e0e-4469-ae19-16be162502b8)
