### ISSUE TITLE
Updated via git pull. Now unable to start AudioCraft.

### ISSUE THREAD

**Issue by Gushousekai195** [GrandaddyShmax/audiocraft_plus#26]
```
Traceback (most recent call last):
  File "C:\Users\mattb\audiocraft_plus\app.py", line 26, in <module>
    import taglib
ModuleNotFoundError: No module named 'taglib'
Press any key to continue . . .
```

I press a key and the cmd window just closes.

**Comment by GrandaddyShmax** [comment]
Are you running this on a mac os? it looks like you are missing the taglib package, either it does not show up on your requirements or you have a mac os

**Comment by leonyp** [comment]
i'm on windows 11 but same No module named 'taglib'

**Comment by Rubenacp** [comment]
Same here. I installed it and I have the same problem: 

First I had this issue:
audiocraft_plus\app.py", line 21, in <module> from pydub import AudioSegment ModuleNotFoundError: No module named 'pydub'

But I instaled 'pydub' manually. After that I have the other issue.

File "C:\audiocraft_plus\app.py", line 26, in <module>
    import taglib
ModuleNotFoundError: No module named 'taglib'
