### ISSUE TITLE
not downloadin models

### ISSUE THREAD

**Issue by 2blackbar** [GrandaddyShmax/audiocraft_plus#34]
Make a video took 1.1086127758026123
video: NsYgICqINIfJ.mp4
batch finished 1 3.945178985595703
Tempfiles currently stored:  33
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "G:\miniconda\envs\audiocraft\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "G:\miniconda\envs\audiocraft\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "G:\miniconda\envs\audiocraft\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "G:\miniconda\envs\audiocraft\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
loading MBD
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 5348ba3b-e321-44cf-8107-28a72b982755)')' thrown while requesting HEAD https://huggingface.co/facebook/musicgen-small/resolve/main/compression_state_dict.bin
Traceback (most recent call last):
  File "G:\miniconda\envs\audiocraft\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\miniconda\envs\audiocraft\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\miniconda\envs\audiocraft\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\miniconda\envs\audiocraft\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\miniconda\envs\audiocraft\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\miniconda\envs\audiocraft\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\miniconda\envs\audiocraft\lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "G:\audiocraft\app.py", line 849, in predict_full
    load_diffusion()
  File "G:\audiocraft\app.py", line 471, in load_diffusion
    MBD = MultiBandDiffusion.get_mbd_musicgen()
  File "G:\audiocraft\audiocraft\models\multibanddiffusion.py", line 73, in get_mbd_musicgen
    codec_model = load_compression_model(name, device=device)
  File "G:\audiocraft\audiocraft\models\loaders.py", line 72, in load_compression_model
    pkg = load_compression_model_ckpt(file_or_url_or_id, cache_dir=cache_dir)
  File "G:\audiocraft\audiocraft\models\loaders.py", line 68, in load_compression_model_ckpt
    return _get_state_dict(file_or_url_or_id, filename="compression_state_dict.bin", cache_dir=cache_dir)
  File "G:\audiocraft\audiocraft\models\loaders.py", line 63, in _get_state_dict
    file = hf_hub_download(repo_id=file_or_url_or_id, filename=filename, cache_dir=cache_dir)
  File "G:\miniconda\envs\audiocraft\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "G:\miniconda\envs\audiocraft\lib\site-packages\huggingface_hub\file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

**Comment by GrandaddyShmax** [comment]
I cannot seem to reproduce your issue, can you explain what you did to get this error?
From my testing it downloads with no issue both with MBD and without

**Comment by zatt** [comment]
I was having this exact same issue earlier when I went to try MBD. I think huggingface was just down. I went to downforeveryoneorjustme.com and it said it was down. I had to retry about 5 times, and it finally worked.
